% genVDCPD.m - 
% Generate uniform density complementary poisson-disc
% or Poisson DISCO sampling
% Usage:
% M = genVDCPD(numMasks, Rmax, vd_exp, alpha, feasiblePoints, shapeOpt, verbose, C, mindist) 
%  INPUTS:
%   numMasks       = # regions (segments) over which to distribute samples
%   Rmax           = reduction factor at kr = kmax
%   vd_exp         = Use density 1 / kr^vd_exp
%   alpha          = anisotropy factor FOVz / FOVy
%   feasiblePoints = [ny nz] matrix of feasible points,
%                    feasiblePoints(i,j) = 1 if (i,j) sample
%                    should be in one traj of M, 0 otherwise
%                    this will be sum(M,3)
%   shapeOpt       = min. dist. criterion, shape generated by a sample
%                    'cross': union of a line through time axis and ellipse in k-space
%                    'l1 ball': weighted l1 ball
%                    'ellipsoid': ellipsoid
%                    'cones': two opposing cones pointing on the time axis
%                    Recommended: cones
%   verbose        = 1 to show some output
%   C              = dt_min / dky_min parameter to balance min distance in time and 
%                    ky
%                    Recommended: 1
%   mindist        = scaling for minimum distance
%                    Recommended: 0 for random, 1 for poisson-disc, or between 0 and 1
%  OUTPUTS:
%   M              = [ny nz nt] sampling pattern. sum(M,3)
%                    should be equal to feasiblePoints
% Evan Levine
% egl@stanford.edu
% Stanford University
function M = genVDCPD(numMasks, Rmax, vd_exp, alph, feasiblePoints, shapeOpt, verbose, C, mindist_scaling)
    if nargin < 9
        mindist_scaling = 1;
    end
    if nargin < 8
        C = 1;
    end
    if nargin < 7
        verbose = 1;
    end
    if strcmp(shapeOpt, 'cross')
        shapeOpt = 0;
    elseif strcmp(shapeOpt, 'l1 ball')
        shapeOpt = 1;
    elseif strcmp(shapeOpt, 'ellipsoid')
        shapeOpt = 2;
    elseif strcmp(shapeOpt, 'cones')
        shapeOpt = 3;
    else
        error(['Please provide a min. distance shape: ''cross'', ''ellipsoid'', ''l1 ball'', or ''cones''']);
    end

    M = genVDCPDMex(numMasks, alph, int32(feasiblePoints), shapeOpt, verbose, C, mindist_scaling, Rmax, vd_exp);
    M = double(M);
end


